### Recuperar todas las Todos
GET https://api-todo-dev-fjja.1.us-1.fl0.io/todos

### Recuperar una Todo por id
GET https://api-todo-dev-fjja.1.us-1.fl0.io/todos/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las Todos por un género
GET http://localhost:1234/todo?genre=ACTION

### Crear una Todo con POST
POST https://api-todo-dev-fjja.1.us-1.fl0.io/todos
Content-Type: application/json
{
  "title": "jeison",
  "done": false
}

### Borrar una Todo 
DELETE http://localhost:1234/todo/64d4d8825d614a4ec5984ae3

### Actualizar una Todo
PATCH https://api-todo-dev-fjja.1.us-1.fl0.io/todos/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json
{
  "title": "jeison",
  "done":"true"
}